---
- hosts: localhost
  tasks:
    - name: sdf
      ping:
    - name: List col
      shell: ansible-galaxy collection list
      REGISTER: col
    - name: printnames
      debug:
        var: printnames
