---
- hosts: localhost
  tasks:
    - name: sdf
      ping:
    - name: List col
      command: "ansible-galaxy collection list"
      register: COUTPUT
      
#     - name: Print return information from the previous task
#       ansible.builtin.debug:
#         msg: "{{ COUTPUT }}"
