---
- hosts: localhost
  tasks:
    - name: sdf
      ping:
    - name: List col
      shell: ansible-galaxy collection list
      register: col
      
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: "{{ col }}"
        verbosity: 2
